defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
    address = ":8000"

[api]
  dashboard = true
  debug = true

[docker]
watch = true
domain = "robertoalegro.com"
exposedByDefault = true

[accessLog]
